[package]
name = "rizzle"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
cookie = "0.17.0"
serde = "1.0.163"
serde_json = "1.0.96"
ureq = { version = "*", features = ["json", "cookies"]}
