[package]
name = "dizzle"
version = "0.1.0"
edition = "2021"
description = "Fast no-javascript alternative Deezer Client"

[dependencies]
serde = "1.0.163"
anyhow = "1.0.71"
alsa = "0.7.0"
eframe = "0.22.0"
toml = "0.7.4"
rizzle = { path = ".." }
serde_derive = "1.0.163"

